#!/bin/bash

echo "hello" >> quotation_command_outputs
"echo" hello >> quotation_command_outputs
"echo hello" >> quotation_command_outputs
echo " hello " >> quotation_command_outputs
echo "" >> quotation_command_outputs
ec"ho hello" >> quotation_command_outputs
"ls -a" >> quotation_command_outputs
exit >> quotation_command_outputs